language: java
jdk:
- openjdk8
- openjdk11
cache:
  directories:
  - "$HOME/.m2/repository/"
before_install:
- git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
- cp target/ci-tooling/maven-settings-for-tinder.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-tinder.xml -P ci
  skip_cleanup: true
  on:
    repo: igniterealtime/tinder
    all_branches: true
env:
  global:
  - secure: Sw6v1DrGt3mpx7rruGc6bIyIICpI/NUq0fbzC3b/A942r1hN20SV/cCdDYkWoUQ0Vj92o9jI7DuwsNtHdI71gSjVEwI+Dc45eSfiDpRHo5c9vdXBmCDhB/En1rCINwKV4NwzglMo/Fjzys5OFTERVHVADebamNnDU0ms6Az1J3I=
  - secure: WmJSdOXX7j2jzrPyCZIbYLQiiyjkgOIQUYhiE8DTokiqzDxqoCdZjCS2gQ5py1cEx107iYIxLlck+AWcWVGddhEZwmVzw4Zgx5b77hmpc/XbF3kR9ntiUKHHLS0IoyJ74YSAtREeNOHwWJ3sieeeyBjlnsJfz429H+afznHGkNg=
